services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3200:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=file:./dev.db
    restart: unless-stopped
