services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3200:3000"
    volumes:
      - .:/appCaravanes
    environment:
      - DATABASE_URL=file:./dev.db
    restart: unless-stopped
